name: Build & Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # every Monday at midnight

permissions:
  packages: write

jobs:
  get_versions:
    name: Get Versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PostgreSQL Versions
        id: get_versions
        run: echo "matrix=$(bash get-postgres-versions.sh)" >> "$GITHUB_OUTPUT"

  push_images:
    name: Push Image - ${{ matrix.version }}
    needs: get_versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.get_versions.outputs.matrix).versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            POSTGRES_TAG=${{ matrix.version }}
          push: true
          pull: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/postgres-multiple-databases:${{ matrix.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ matrix.version }}
